# Shell variables
# Generated by 'wal'
wallpaper='/home/alexis/Imágenes/wall/1.jpg'

# Special
background='#1c1c1c'
foreground='#ece4e3'
cursor='#ece4e3'

# Colors
color0='#1c1c1c'
color1='#6DB8CD'
color2='#70B5C9'
color3='#F69986'
color4='#F5A196'
color5='#EBADA4'
color6='#A0C9D4'
color7='#ece4e3'
color8='#a59f9e'
color9='#6DB8CD'
color10='#70B5C9'
color11='#F69986'
color12='#F5A196'
color13='#EBADA4'
color14='#A0C9D4'
color15='#ece4e3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
